# Generated by Django 2.2 on 2020-04-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('remote', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('angel', 'AngelList'), ('indeed', 'Indeed.com'), ('remoteok', 'RemoteOK')], max_length=100)),
                ('description', models.TextField()),
                ('job_type', models.CharField(max_length=25)),
                ('salary', models.CharField(max_length=50)),
                ('locations', models.TextField()),
                ('experience', models.FloatField()),
                ('skills', models.TextField()),
                ('posted_at', models.DateField()),
            ],
        ),
    ]
